//go:build go1.22

// Package settings provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package settings

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ListarSettingsParamsSort.
const (
	Key           ListarSettingsParamsSort = "key"
	Keyasc        ListarSettingsParamsSort = "key,asc"
	Keydesc       ListarSettingsParamsSort = "key,desc"
	UpdatedAt     ListarSettingsParamsSort = "updatedAt"
	UpdatedAtasc  ListarSettingsParamsSort = "updatedAt,asc"
	UpdatedAtdesc ListarSettingsParamsSort = "updatedAt,desc"
)

// Valid indicates whether the value is a known member of the ListarSettingsParamsSort enum.
func (e ListarSettingsParamsSort) Valid() bool {
	switch e {
	case Key:
		return true
	case Keyasc:
		return true
	case Keydesc:
		return true
	case UpdatedAt:
		return true
	case UpdatedAtasc:
		return true
	case UpdatedAtdesc:
		return true
	default:
		return false
	}
}

// PageMeta Los metadatos de una pagina. `size` es el tamano EFECTIVO: si el cliente
// pidio un millon, aqui dice 100.
type PageMeta struct {
	Number        int   `json:"number"`
	Size          int   `json:"size"`
	TotalElements int64 `json:"totalElements"`
	TotalPages    int   `json:"totalPages"`
}

// Problem La forma unica de error de toda la API (RFC 7807) con dos campos
// propios: `code`, estable y en mayusculas, es lo que el cliente
// interpreta; `traceId` es lo que se busca en el log.
// Ver docs/04-reglas-de-crud.md seccion 6.
type Problem struct {
	Code   string  `json:"code"`
	Detail *string `json:"detail,omitempty"`
	Errors *[]struct {
		Code    string `json:"code"`
		Field   string `json:"field"`
		Message string `json:"message"`
	} `json:"errors,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	TraceId  string  `json:"traceId"`
	Type     *string `json:"type,omitempty"`
}

// Setting defines model for Setting.
type Setting struct {
	// IsPublic Que una clave sea publica es una decision explicita. Por omision es
	// privada: aqui viven tambien llaves de terceros y correos internos.
	IsPublic  bool      `json:"isPublic"`
	Key       string    `json:"key"`
	UpdatedAt time.Time `json:"updatedAt"`

	// UpdatedBy Lo llena la plataforma, no el codigo de negocio. Es nulo solo en las
	// filas que sembro la migracion inicial: nadie las escribio.
	UpdatedBy *openapi_types.UUID `json:"updatedBy"`

	// Value JSON libre. El esquema por clave se valida en el servidor a partir
	// de la fase 4, y hasta entonces darle un tipo aqui seria describir
	// algo que nadie comprueba.
	Value interface{} `json:"value"`

	// Version Se devuelve tambien como `ETag`.
	Version int `json:"version"`
}

// SettingModificacion El cuerpo de reemplazo. No trae `key`: la clave es la identidad del
// recurso y viaja en la ruta. Aceptarla aqui abriria la puerta a un `PUT`
// que renombra la fila que estaba editando otro.
type SettingModificacion struct {
	IsPublic *bool       `json:"isPublic,omitempty"`
	Value    interface{} `json:"value"`
}

// SettingNuevo El cuerpo de alta. No acepta `version` ni `updatedBy`: no son del
// cliente, y mandarlos es un `400` y no un campo ignorado en silencio.
type SettingNuevo struct {
	IsPublic *bool       `json:"isPublic,omitempty"`
	Key      string      `json:"key"`
	Value    interface{} `json:"value"`
}

// SettingsMap Clave a valor. El valor es JSON libre: el esquema por clave se valida en
// el servidor a partir de la fase 4, y hasta entonces darle un tipo aqui
// seria describir algo que nadie comprueba.
type SettingsMap map[string]interface{}

// SettingsPage El envoltorio de toda coleccion de esta API. Nunca un array pelado en la
// raiz: agregar metadatos despues rompe a todos los clientes a la vez. Una
// coleccion vacia sale como `[]`, jamas como `null`.
type SettingsPage struct {
	Content []Setting `json:"content"`

	// Page Los metadatos de una pagina. `size` es el tamano EFECTIVO: si el cliente
	// pidio un millon, aqui dice 100.
	Page PageMeta `json:"page"`
}

// Page defines model for Page.
type Page = int

// Size defines model for Size.
type Size = int

// ListarSettingsParams defines parameters for ListarSettings.
type ListarSettingsParams struct {
	// Page Numero de pagina, base 0.
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Size Tamano de pagina. El tope es **duro**: pedir mas devuelve 100 y
	// `page.size` reporta el efectivo. Sin el, `?size=1000000` seria una
	// negacion de servicio de una linea.
	Size *Size `form:"size,omitempty" json:"size,omitempty"`

	// Sort `campo,dir` con `dir` en `asc` (por omision) o `desc`. Se puede
	// repetir para ordenar por varios criterios. Todo orden termina con un
	// desempate estable por `key`: sin el, dos filas con el mismo
	// `updatedAt` se repiten o se pierden entre paginas.
	Sort *[]ListarSettingsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// IsPublic Filtra por visibilidad. Es el unico filtro declarado.
	IsPublic *bool `form:"isPublic,omitempty" json:"isPublic,omitempty"`
}

// ListarSettingsParamsSort defines parameters for ListarSettings.
type ListarSettingsParamsSort string

// ReemplazarSettingParams defines parameters for ReemplazarSetting.
type ReemplazarSettingParams struct {
	// IfMatch El `ETag` que devolvio la lectura. `*` no se acepta.
	IfMatch string `json:"If-Match"`
}

// CrearSettingJSONRequestBody defines body for CrearSetting for application/json ContentType.
type CrearSettingJSONRequestBody = SettingNuevo

// ReemplazarSettingJSONRequestBody defines body for ReemplazarSetting for application/json ContentType.
type ReemplazarSettingJSONRequestBody = SettingModificacion

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListarSettingsPublicas La configuracion publica del sitio
	// (GET /public/settings)
	ListarSettingsPublicas(w http.ResponseWriter, r *http.Request)
	// ListarSettings Listar la configuracion, incluidas las claves privadas
	// (GET /settings)
	ListarSettings(w http.ResponseWriter, r *http.Request, params ListarSettingsParams)
	// CrearSetting Crear una clave de configuracion
	// (POST /settings)
	CrearSetting(w http.ResponseWriter, r *http.Request)
	// LeerSetting Leer una clave
	// (GET /settings/{key})
	LeerSetting(w http.ResponseWriter, r *http.Request, key string)
	// ReemplazarSetting Reemplazar el valor de una clave
	// (PUT /settings/{key})
	ReemplazarSetting(w http.ResponseWriter, r *http.Request, key string, params ReemplazarSettingParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListarSettingsPublicas operation middleware
func (siw *ServerInterfaceWrapper) ListarSettingsPublicas(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListarSettingsPublicas(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListarSettings operation middleware
func (siw *ServerInterfaceWrapper) ListarSettings(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListarSettingsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "size", r.URL.Query(), &params.Size, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "size", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "isPublic" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "isPublic", r.URL.Query(), &params.IsPublic, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "isPublic"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "isPublic", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListarSettings(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CrearSetting operation middleware
func (siw *ServerInterfaceWrapper) CrearSetting(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CrearSetting(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LeerSetting operation middleware
func (siw *ServerInterfaceWrapper) LeerSetting(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LeerSetting(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReemplazarSetting operation middleware
func (siw *ServerInterfaceWrapper) ReemplazarSetting(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ReemplazarSettingParams

	headers := r.Header

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReemplazarSetting(w, r, key, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/public/settings", wrapper.ListarSettingsPublicas)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/settings", wrapper.ListarSettings)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/settings", wrapper.CrearSetting)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/settings/{key}", wrapper.LeerSetting)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/settings/{key}", wrapper.ReemplazarSetting)

	return m
}
