//go:build go1.22

// Package content provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package content

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ListarPaginasParamsSort.
const (
	ListarPaginasParamsSortSlug          ListarPaginasParamsSort = "slug"
	ListarPaginasParamsSortSlugasc       ListarPaginasParamsSort = "slug,asc"
	ListarPaginasParamsSortSlugdesc      ListarPaginasParamsSort = "slug,desc"
	ListarPaginasParamsSortUpdatedAt     ListarPaginasParamsSort = "updatedAt"
	ListarPaginasParamsSortUpdatedAtasc  ListarPaginasParamsSort = "updatedAt,asc"
	ListarPaginasParamsSortUpdatedAtdesc ListarPaginasParamsSort = "updatedAt,desc"
)

// Valid indicates whether the value is a known member of the ListarPaginasParamsSort enum.
func (e ListarPaginasParamsSort) Valid() bool {
	switch e {
	case ListarPaginasParamsSortSlug:
		return true
	case ListarPaginasParamsSortSlugasc:
		return true
	case ListarPaginasParamsSortSlugdesc:
		return true
	case ListarPaginasParamsSortUpdatedAt:
		return true
	case ListarPaginasParamsSortUpdatedAtasc:
		return true
	case ListarPaginasParamsSortUpdatedAtdesc:
		return true
	default:
		return false
	}
}

// Defines values for ListarVersionesParamsSort.
const (
	Number     ListarVersionesParamsSort = "number"
	Numberasc  ListarVersionesParamsSort = "number,asc"
	Numberdesc ListarVersionesParamsSort = "number,desc"
)

// Valid indicates whether the value is a known member of the ListarVersionesParamsSort enum.
func (e ListarVersionesParamsSort) Valid() bool {
	switch e {
	case Number:
		return true
	case Numberasc:
		return true
	case Numberdesc:
		return true
	default:
		return false
	}
}

// Bloque Una pieza de la pagina. `type` elige el componente que la dibuja y el
// esquema que valida sus `props`; los tipos viven en el catalogo del
// modulo `content` (`api/internal/modules/content/bloques/`), que es lo
// que un fork edita para cambiar el lenguaje visual del sitio.
//
// `props` se declara aqui como objeto libre porque su forma depende del
// tipo: la valida el servidor al guardar, contra el esquema del catalogo.
type Bloque struct {
	// Id Unico dentro de la pagina. Lo usa el editor para seguir al bloque al moverlo.
	Id    string                 `json:"id"`
	Props map[string]interface{} `json:"props"`
	Type  string                 `json:"type"`
}

// PageMeta Los metadatos de una pagina. `size` es el tamano EFECTIVO: si el cliente
// pidio un millon, aqui dice 100.
type PageMeta struct {
	Number        int   `json:"number"`
	Size          int   `json:"size"`
	TotalElements int64 `json:"totalElements"`
	TotalPages    int   `json:"totalPages"`
}

// Pagina La pagina con su borrador, que es la version de numero mayor. Lo
// publicado se identifica por `publishedVersionId`; si coincide con
// `draftVersionId`, no hay cambios sin publicar.
type Pagina struct {
	Blocks         []Bloque           `json:"blocks"`
	CreatedAt      time.Time          `json:"createdAt"`
	DraftNumber    int                `json:"draftNumber"`
	DraftVersionId openapi_types.UUID `json:"draftVersionId"`
	Id             openapi_types.UUID `json:"id"`

	// Note La nota del guardado que creo el borrador.
	Note            *string `json:"note"`
	PublishedNumber *int    `json:"publishedNumber"`

	// PublishedVersionId Nulo si la pagina nunca se publico.
	PublishedVersionId *openapi_types.UUID `json:"publishedVersionId"`
	SeoDescription     *string             `json:"seoDescription"`
	SeoTitle           *string             `json:"seoTitle"`
	Slug               string              `json:"slug"`
	Title              string              `json:"title"`
	UpdatedAt          time.Time           `json:"updatedAt"`
	UpdatedBy          *openapi_types.UUID `json:"updatedBy"`

	// Version Se devuelve tambien como `ETag`.
	Version int `json:"version"`
}

// PaginaModificacion El cuerpo de un guardado. Reemplaza el borrador completo: lo que no
// venga no se conserva de la version anterior.
type PaginaModificacion struct {
	Blocks         []Bloque `json:"blocks"`
	Note           *string  `json:"note,omitempty"`
	SeoDescription *string  `json:"seoDescription,omitempty"`
	SeoTitle       *string  `json:"seoTitle,omitempty"`
	Slug           string   `json:"slug"`
	Title          string   `json:"title"`
}

// PaginaNueva El cuerpo de alta. No acepta `version`, `id` ni nada de auditoria:
// mandarlos es un `400`, no un campo ignorado en silencio.
type PaginaNueva struct {
	Blocks []Bloque `json:"blocks"`

	// Note Para que sirvio este guardado, por ejemplo "cambie el hero".
	Note           *string `json:"note,omitempty"`
	SeoDescription *string `json:"seoDescription,omitempty"`
	SeoTitle       *string `json:"seoTitle,omitempty"`
	Slug           string  `json:"slug"`
	Title          string  `json:"title"`
}

// PaginaPublica Solo lo que la landing necesita para dibujar la pagina.
type PaginaPublica struct {
	Blocks         []Bloque `json:"blocks"`
	SeoDescription *string  `json:"seoDescription"`
	SeoTitle       *string  `json:"seoTitle"`
	Slug           string   `json:"slug"`
	Title          string   `json:"title"`
}

// PaginaResumen defines model for PaginaResumen.
type PaginaResumen struct {
	// DraftNumber El numero de la version mas nueva.
	DraftNumber int                `json:"draftNumber"`
	Id          openapi_types.UUID `json:"id"`

	// PublishedNumber El numero de la version publicada; nulo si nunca se publico.
	PublishedNumber *int   `json:"publishedNumber"`
	Slug            string `json:"slug"`

	// Title El titulo del borrador, que puede no ser el publicado.
	Title     string              `json:"title"`
	UpdatedAt time.Time           `json:"updatedAt"`
	UpdatedBy *openapi_types.UUID `json:"updatedBy"`

	// Version La del `ETag`. Sube con cada guardado.
	Version int `json:"version"`
}

// PaginasPage El envoltorio de coleccion. Ver `SettingsPage`.
type PaginasPage struct {
	Content []PaginaResumen `json:"content"`

	// Page Los metadatos de una pagina. `size` es el tamano EFECTIVO: si el cliente
	// pidio un millon, aqui dice 100.
	Page PageMeta `json:"page"`
}

// Problem La forma unica de error de toda la API (RFC 7807) con dos campos
// propios: `code`, estable y en mayusculas, es lo que el cliente
// interpreta; `traceId` es lo que se busca en el log.
// Ver docs/04-reglas-de-crud.md seccion 6.
type Problem struct {
	Code   string  `json:"code"`
	Detail *string `json:"detail,omitempty"`
	Errors *[]struct {
		Code    string `json:"code"`
		Field   string `json:"field"`
		Message string `json:"message"`
	} `json:"errors,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	TraceId  string  `json:"traceId"`
	Type     *string `json:"type,omitempty"`
}

// Publicacion defines model for Publicacion.
type Publicacion struct {
	// VersionId Una version de ESTA pagina.
	VersionId openapi_types.UUID `json:"versionId"`
}

// VersionResumen defines model for VersionResumen.
type VersionResumen struct {
	CreatedAt time.Time           `json:"createdAt"`
	CreatedBy *openapi_types.UUID `json:"createdBy"`
	Id        openapi_types.UUID  `json:"id"`
	Note      *string             `json:"note"`
	Number    int                 `json:"number"`

	// Published Si es la version que ve el publico.
	Published bool   `json:"published"`
	Title     string `json:"title"`
}

// VersionesPage defines model for VersionesPage.
type VersionesPage struct {
	Content []VersionResumen `json:"content"`

	// Page Los metadatos de una pagina. `size` es el tamano EFECTIVO: si el cliente
	// pidio un millon, aqui dice 100.
	Page PageMeta `json:"page"`
}

// CuentaId defines model for CuentaId.
type CuentaId = openapi_types.UUID

// IfMatch defines model for IfMatch.
type IfMatch = string

// MedioId defines model for MedioId.
type MedioId = openapi_types.UUID

// Page defines model for Page.
type Page = int

// PaginaId defines model for PaginaId.
type PaginaId = openapi_types.UUID

// RolKey defines model for RolKey.
type RolKey = string

// Size defines model for Size.
type Size = int

// Slug defines model for Slug.
type Slug = string

// ListarPaginasParams defines parameters for ListarPaginas.
type ListarPaginasParams struct {
	// Page Numero de pagina, base 0.
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Size Tamano de pagina. El tope es **duro**: pedir mas devuelve 100 y
	// `page.size` reporta el efectivo. Sin el, `?size=1000000` seria una
	// negacion de servicio de una linea.
	Size *Size `form:"size,omitempty" json:"size,omitempty"`

	// Sort `campo,dir` con `dir` en `asc` (por omision) o `desc`. Todo orden
	// termina con un desempate estable por `id`.
	Sort *[]ListarPaginasParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Published Filtra por si la pagina tiene una version publicada.
	Published *bool `form:"published,omitempty" json:"published,omitempty"`
}

// ListarPaginasParamsSort defines parameters for ListarPaginas.
type ListarPaginasParamsSort string

// GuardarPaginaParams defines parameters for GuardarPagina.
type GuardarPaginaParams struct {
	// IfMatch El `ETag` que devolvio la lectura. `*` no se acepta.
	IfMatch IfMatch `json:"If-Match"`
}

// ListarVersionesParams defines parameters for ListarVersiones.
type ListarVersionesParams struct {
	// Page Numero de pagina, base 0.
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Size Tamano de pagina. El tope es **duro**: pedir mas devuelve 100 y
	// `page.size` reporta el efectivo. Sin el, `?size=1000000` seria una
	// negacion de servicio de una linea.
	Size *Size `form:"size,omitempty" json:"size,omitempty"`

	// Sort `campo,dir`. Por omision `number,desc`. El numero es unico dentro
	// de la pagina, asi que tambien es el desempate.
	Sort *[]ListarVersionesParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// ListarVersionesParamsSort defines parameters for ListarVersiones.
type ListarVersionesParamsSort string

// CrearPaginaJSONRequestBody defines body for CrearPagina for application/json ContentType.
type CrearPaginaJSONRequestBody = PaginaNueva

// GuardarPaginaJSONRequestBody defines body for GuardarPagina for application/json ContentType.
type GuardarPaginaJSONRequestBody = PaginaModificacion

// PublicarPaginaJSONRequestBody defines body for PublicarPagina for application/json ContentType.
type PublicarPaginaJSONRequestBody = Publicacion

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListarPaginas Listar las paginas
	// (GET /pages)
	ListarPaginas(w http.ResponseWriter, r *http.Request, params ListarPaginasParams)
	// CrearPagina Crear una pagina
	// (POST /pages)
	CrearPagina(w http.ResponseWriter, r *http.Request)
	// BorrarPagina Borrar una pagina y todas sus versiones
	// (DELETE /pages/{id})
	BorrarPagina(w http.ResponseWriter, r *http.Request, id PaginaId)
	// LeerPagina Leer una pagina con su ultima version
	// (GET /pages/{id})
	LeerPagina(w http.ResponseWriter, r *http.Request, id PaginaId)
	// GuardarPagina Guardar una pagina, que crea una version nueva
	// (PUT /pages/{id})
	GuardarPagina(w http.ResponseWriter, r *http.Request, id PaginaId, params GuardarPaginaParams)
	// PublicarPagina Publicar una version
	// (POST /pages/{id}/publish)
	PublicarPagina(w http.ResponseWriter, r *http.Request, id PaginaId)
	// ListarVersiones Listar las versiones de una pagina
	// (GET /pages/{id}/versions)
	ListarVersiones(w http.ResponseWriter, r *http.Request, id PaginaId, params ListarVersionesParams)
	// LeerPaginaPublica La version publicada de una pagina
	// (GET /public/pages/{slug})
	LeerPaginaPublica(w http.ResponseWriter, r *http.Request, slug Slug)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListarPaginas operation middleware
func (siw *ServerInterfaceWrapper) ListarPaginas(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListarPaginasParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "size", r.URL.Query(), &params.Size, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "size", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "published" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "published", r.URL.Query(), &params.Published, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "published"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "published", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListarPaginas(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CrearPagina operation middleware
func (siw *ServerInterfaceWrapper) CrearPagina(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CrearPagina(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BorrarPagina operation middleware
func (siw *ServerInterfaceWrapper) BorrarPagina(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id PaginaId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BorrarPagina(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LeerPagina operation middleware
func (siw *ServerInterfaceWrapper) LeerPagina(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id PaginaId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LeerPagina(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GuardarPagina operation middleware
func (siw *ServerInterfaceWrapper) GuardarPagina(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id PaginaId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GuardarPaginaParams

	headers := r.Header

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch IfMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GuardarPagina(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PublicarPagina operation middleware
func (siw *ServerInterfaceWrapper) PublicarPagina(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id PaginaId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PublicarPagina(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListarVersiones operation middleware
func (siw *ServerInterfaceWrapper) ListarVersiones(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id PaginaId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListarVersionesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "size", r.URL.Query(), &params.Size, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "size", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListarVersiones(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LeerPaginaPublica operation middleware
func (siw *ServerInterfaceWrapper) LeerPaginaPublica(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug Slug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LeerPaginaPublica(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/public/pages/{slug}", wrapper.LeerPaginaPublica)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/pages", wrapper.ListarPaginas)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/pages", wrapper.CrearPagina)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/pages/{id}", wrapper.BorrarPagina)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/pages/{id}", wrapper.LeerPagina)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/pages/{id}", wrapper.GuardarPagina)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/pages/{id}/versions", wrapper.ListarVersiones)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/pages/{id}/publish", wrapper.PublicarPagina)

	return m
}
