//go:build go1.22

// Package identity provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package identity

import (
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Credenciales `additionalProperties: false` a proposito: un campo de mas es un `400` y
// no algo que se ignora en silencio. Es el mismo criterio que
// `SettingNuevo`.
type Credenciales struct {
	// Email No se normaliza a minusculas en el cliente ni en el servidor: quien
	// garantiza que `Ana@casa.com` y `ana@casa.com` son la misma cuenta es
	// el tipo `citext` de la columna.
	Email string `json:"email"`

	// Password El maximo no es una regla de seguridad sino de recursos: argon2
	// procesa lo que le den, y un campo de diez megas ocupa un nucleo
	// entero.
	Password string `json:"password"`
}

// Perfil Lo unico que el frontend sabe del usuario. `permissions[]` son los
// efectivos, ya resueltos por sus roles.
type Perfil struct {
	DisplayName string             `json:"displayName"`
	Email       string             `json:"email"`
	Id          openapi_types.UUID `json:"id"`

	// Permissions Vacio es `[]`, jamas `null`: un cliente que hace `.includes()` sobre
	// null revienta, y la diferencia entre "sin permisos" y "no vino el
	// campo" no le sirve a nadie.
	Permissions []string `json:"permissions"`
	Roles       []string `json:"roles"`
}

// Problem La forma unica de error de toda la API (RFC 7807) con dos campos
// propios: `code`, estable y en mayusculas, es lo que el cliente
// interpreta; `traceId` es lo que se busca en el log.
// Ver docs/04-reglas-de-crud.md seccion 6.
type Problem struct {
	Code   string  `json:"code"`
	Detail *string `json:"detail,omitempty"`
	Errors *[]struct {
		Code    string `json:"code"`
		Field   string `json:"field"`
		Message string `json:"message"`
	} `json:"errors,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	TraceId  string  `json:"traceId"`
	Type     *string `json:"type,omitempty"`
}

// PaginaId defines model for PaginaId.
type PaginaId = openapi_types.UUID

// Slug defines model for Slug.
type Slug = string

// XsrfToken defines model for XsrfToken.
type XsrfToken = string

// IniciarSesionParams defines parameters for IniciarSesion.
type IniciarSesionParams struct {
	// XXSRFTOKEN El valor de la cookie `XSRF-TOKEN`, reenviado a mano. Es el doble envio:
	// quien no puede leer la cookie —otro origen— no puede forjar la cabecera.
	//
	// Se declara aqui, y no solo en el middleware, para que el cliente
	// generado sepa que la operacion la necesita.
	XXSRFTOKEN XsrfToken `json:"X-XSRF-TOKEN"`
}

// CerrarSesionParams defines parameters for CerrarSesion.
type CerrarSesionParams struct {
	// XXSRFTOKEN El valor de la cookie `XSRF-TOKEN`, reenviado a mano. Es el doble envio:
	// quien no puede leer la cookie —otro origen— no puede forjar la cabecera.
	//
	// Se declara aqui, y no solo en el middleware, para que el cliente
	// generado sepa que la operacion la necesita.
	XXSRFTOKEN XsrfToken `json:"X-XSRF-TOKEN"`
}

// RenovarSesionParams defines parameters for RenovarSesion.
type RenovarSesionParams struct {
	// XXSRFTOKEN El valor de la cookie `XSRF-TOKEN`, reenviado a mano. Es el doble envio:
	// quien no puede leer la cookie —otro origen— no puede forjar la cabecera.
	//
	// Se declara aqui, y no solo en el middleware, para que el cliente
	// generado sepa que la operacion la necesita.
	XXSRFTOKEN XsrfToken `json:"X-XSRF-TOKEN"`
}

// IniciarSesionJSONRequestBody defines body for IniciarSesion for application/json ContentType.
type IniciarSesionJSONRequestBody = Credenciales

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// IniciarSesion Iniciar sesion
	// (POST /auth/login)
	IniciarSesion(w http.ResponseWriter, r *http.Request, params IniciarSesionParams)
	// CerrarSesion Cerrar la sesion
	// (POST /auth/logout)
	CerrarSesion(w http.ResponseWriter, r *http.Request, params CerrarSesionParams)
	// MiPerfil Quien tiene esta sesion
	// (GET /auth/me)
	MiPerfil(w http.ResponseWriter, r *http.Request)
	// RenovarSesion Renovar la sesion
	// (POST /auth/refresh)
	RenovarSesion(w http.ResponseWriter, r *http.Request, params RenovarSesionParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// IniciarSesion operation middleware
func (siw *ServerInterfaceWrapper) IniciarSesion(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params IniciarSesionParams

	headers := r.Header

	// ------------- Required header parameter "X-XSRF-TOKEN" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-XSRF-TOKEN")]; found {
		var XXSRFTOKEN XsrfToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-XSRF-TOKEN", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-XSRF-TOKEN", valueList[0], &XXSRFTOKEN, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-XSRF-TOKEN", Err: err})
			return
		}

		params.XXSRFTOKEN = XXSRFTOKEN

	} else {
		err := fmt.Errorf("Header parameter X-XSRF-TOKEN is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-XSRF-TOKEN", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IniciarSesion(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CerrarSesion operation middleware
func (siw *ServerInterfaceWrapper) CerrarSesion(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CerrarSesionParams

	headers := r.Header

	// ------------- Required header parameter "X-XSRF-TOKEN" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-XSRF-TOKEN")]; found {
		var XXSRFTOKEN XsrfToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-XSRF-TOKEN", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-XSRF-TOKEN", valueList[0], &XXSRFTOKEN, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-XSRF-TOKEN", Err: err})
			return
		}

		params.XXSRFTOKEN = XXSRFTOKEN

	} else {
		err := fmt.Errorf("Header parameter X-XSRF-TOKEN is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-XSRF-TOKEN", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CerrarSesion(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MiPerfil operation middleware
func (siw *ServerInterfaceWrapper) MiPerfil(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MiPerfil(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RenovarSesion operation middleware
func (siw *ServerInterfaceWrapper) RenovarSesion(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params RenovarSesionParams

	headers := r.Header

	// ------------- Required header parameter "X-XSRF-TOKEN" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-XSRF-TOKEN")]; found {
		var XXSRFTOKEN XsrfToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-XSRF-TOKEN", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-XSRF-TOKEN", valueList[0], &XXSRFTOKEN, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-XSRF-TOKEN", Err: err})
			return
		}

		params.XXSRFTOKEN = XXSRFTOKEN

	} else {
		err := fmt.Errorf("Header parameter X-XSRF-TOKEN is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-XSRF-TOKEN", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RenovarSesion(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/login", wrapper.IniciarSesion)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/me", wrapper.MiPerfil)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/refresh", wrapper.RenovarSesion)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/logout", wrapper.CerrarSesion)

	return m
}
