//go:build go1.22

// Package media provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package media

import (
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for MedioMime.
const (
	Imagejpeg MedioMime = "image/jpeg"
	Imagepng  MedioMime = "image/png"
	Imagewebp MedioMime = "image/webp"
)

// Valid indicates whether the value is a known member of the MedioMime enum.
func (e MedioMime) Valid() bool {
	switch e {
	case Imagejpeg:
		return true
	case Imagepng:
		return true
	case Imagewebp:
		return true
	default:
		return false
	}
}

// Medio Una imagen subida. No tiene `version` ni `updatedAt`: un registro no se
// modifica nunca, porque el archivo ES su contenido.
type Medio struct {
	CreatedAt time.Time           `json:"createdAt"`
	CreatedBy *openapi_types.UUID `json:"createdBy"`
	Height    int                 `json:"height"`
	Id        openapi_types.UUID  `json:"id"`
	Mime      MedioMime           `json:"mime"`

	// OriginalName El nombre con el que se subio la PRIMERA vez. Una segunda subida con
	// otro nombre devuelve el registro existente y no lo cambia.
	OriginalName *string `json:"originalName"`

	// Sha256 El SHA-256 de los bytes, en hexadecimal.
	Sha256    string `json:"sha256"`
	SizeBytes int64  `json:"sizeBytes"`

	// Url Donde se sirven los bytes. Es lo que va en un `<img>`.
	Url   string `json:"url"`
	Width int    `json:"width"`
}

// MedioMime defines model for Medio.Mime.
type MedioMime string

// Problem La forma unica de error de toda la API (RFC 7807) con dos campos
// propios: `code`, estable y en mayusculas, es lo que el cliente
// interpreta; `traceId` es lo que se busca en el log.
// Ver docs/04-reglas-de-crud.md seccion 6.
type Problem struct {
	Code   string  `json:"code"`
	Detail *string `json:"detail,omitempty"`
	Errors *[]struct {
		Code    string `json:"code"`
		Field   string `json:"field"`
		Message string `json:"message"`
	} `json:"errors,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	TraceId  string  `json:"traceId"`
	Type     *string `json:"type,omitempty"`
}

// CuentaId defines model for CuentaId.
type CuentaId = openapi_types.UUID

// MedioId defines model for MedioId.
type MedioId = openapi_types.UUID

// PaginaId defines model for PaginaId.
type PaginaId = openapi_types.UUID

// RolKey defines model for RolKey.
type RolKey = string

// Slug defines model for Slug.
type Slug = string

// SubirMedioMultipartBody defines parameters for SubirMedio.
type SubirMedioMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// SubirMedioMultipartRequestBody defines body for SubirMedio for multipart/form-data ContentType.
type SubirMedioMultipartRequestBody SubirMedioMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// SubirMedio Subir una imagen
	// (POST /media)
	SubirMedio(w http.ResponseWriter, r *http.Request)
	// LeerMedio Leer los datos de una imagen
	// (GET /media/{id})
	LeerMedio(w http.ResponseWriter, r *http.Request, id MedioId)
	// LeerMedioPublico Los bytes de una imagen
	// (GET /public/media/{id})
	LeerMedioPublico(w http.ResponseWriter, r *http.Request, id MedioId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// SubirMedio operation middleware
func (siw *ServerInterfaceWrapper) SubirMedio(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubirMedio(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LeerMedio operation middleware
func (siw *ServerInterfaceWrapper) LeerMedio(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id MedioId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LeerMedio(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LeerMedioPublico operation middleware
func (siw *ServerInterfaceWrapper) LeerMedioPublico(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id MedioId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LeerMedioPublico(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/media", wrapper.SubirMedio)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/media/{id}", wrapper.LeerMedio)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/public/media/{id}", wrapper.LeerMedioPublico)

	return m
}
